#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Sphinx configuration for foxBMS ASPICE Documentation
Generated by PARVIS-AiDoc-Generator v1.0.0
Date: 2025-12-16

This configuration creates comprehensive ASPICE-compliant documentation
integrating V-Model process documents, requirements, and traceability.
"""

import os
import sys
from datetime import datetime

# Project information
project = 'foxBMS Battery Management System'
copyright = f'2025, Fraunhofer-Gesellschaft. ASPICE Level 2 Compliant'
author = 'foxBMS Team & PARVIS AI'
version = '2.0.0'
release = '2.0.0-aspice'

# Extensions
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.graphviz',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.ifconfig',
    'sphinx_rtd_theme',
    # 'sphinxcontrib.plantuml',  # Uncomment if PlantUML is available
    # 'breathe',  # Uncomment for Doxygen integration
]

# Breathe configuration for Doxygen integration (if available)
# breathe_projects = {"foxBMS": "../doxygen/xml"}
# breathe_default_project = "foxBMS"

# Theme configuration
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Static files
html_static_path = ['_static']
html_css_files = ['custom.css']

# HTML output settings
html_title = 'foxBMS ASPICE Documentation'
html_short_title = 'foxBMS Docs'
html_show_sourcelink = False
html_show_sphinx = False

# Source settings
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}
master_doc = 'index'

# Language
language = 'en'

# Exclude patterns
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# Pygments style
pygments_style = 'sphinx'

# LaTeX output (for PDF generation)
latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '11pt',
    'preamble': r'''
\usepackage{charter}
\usepackage[defaultsans]{lato}
\usepackage{inconsolata}
''',
}

latex_documents = [
    (master_doc, 'foxBMS-ASPICE.tex', 'foxBMS ASPICE Documentation',
     'foxBMS Team', 'manual'),
]

# Graphviz settings
graphviz_output_format = 'svg'

# Todo extension
todo_include_todos = True

# Custom sidebar
html_sidebars = {
    '**': [
        'globaltoc.html',
        'relations.html',
        'searchbox.html',
    ]
}

# ASPICE-specific configuration
aspice_level = 2
iso26262_asil = 'D'
project_phase = 'Verification Complete'

# Custom context for templates
html_context = {
    'aspice_level': aspice_level,
    'iso26262_asil': iso26262_asil,
    'project_phase': project_phase,
    'generation_date': datetime.now().strftime('%Y-%m-%d'),
}
