#!/bin/bash
# foxBMS Documentation Build Script
# Generated by PARVIS-AiDoc-Generator v1.0.0
# Date: 2025-12-16

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_DIR="$SCRIPT_DIR"

echo "=========================================="
echo "foxBMS Documentation Build System"
echo "=========================================="
echo "Output Directory: $OUTPUT_DIR"
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to check if command exists
check_command() {
    if command -v $1 &> /dev/null; then
        echo -e "${GREEN}[OK]${NC} $1 found"
        return 0
    else
        echo -e "${YELLOW}[MISSING]${NC} $1 not found"
        return 1
    fi
}

# Function to build Doxygen documentation
build_doxygen() {
    echo ""
    echo "Building Doxygen API Documentation..."
    echo "--------------------------------------"

    if check_command doxygen; then
        cd "$OUTPUT_DIR"
        doxygen Doxyfile

        if [ -f "$OUTPUT_DIR/doxygen/html/index.html" ]; then
            echo -e "${GREEN}[SUCCESS]${NC} Doxygen documentation generated"
            echo "  Output: $OUTPUT_DIR/doxygen/html/index.html"
        else
            echo -e "${RED}[ERROR]${NC} Doxygen build failed"
            return 1
        fi
    else
        echo -e "${YELLOW}[SKIP]${NC} Doxygen not installed. Install with: sudo apt install doxygen graphviz"
    fi
}

# Function to build Sphinx documentation
build_sphinx() {
    echo ""
    echo "Building Sphinx Process Documentation..."
    echo "-----------------------------------------"

    if check_command sphinx-build; then
        cd "$OUTPUT_DIR/sphinx"
        sphinx-build -b html . _build/html

        if [ -f "$OUTPUT_DIR/sphinx/_build/html/index.html" ]; then
            echo -e "${GREEN}[SUCCESS]${NC} Sphinx documentation generated"
            echo "  Output: $OUTPUT_DIR/sphinx/_build/html/index.html"
        else
            echo -e "${RED}[ERROR]${NC} Sphinx build failed"
            return 1
        fi
    else
        echo -e "${YELLOW}[SKIP]${NC} Sphinx not installed. Install with: pip install sphinx sphinx-rtd-theme"
        echo "       Creating placeholder Sphinx output..."
        mkdir -p "$OUTPUT_DIR/sphinx/_build/html"
        cat > "$OUTPUT_DIR/sphinx/_build/html/index.html" << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>Sphinx Documentation - Build Required</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
        .warning { background: #fff3cd; border: 1px solid #ffc107; padding: 20px; border-radius: 8px; }
        code { background: #f4f4f4; padding: 2px 6px; border-radius: 4px; }
    </style>
</head>
<body>
    <h1>Sphinx Documentation</h1>
    <div class="warning">
        <h3>Build Required</h3>
        <p>Sphinx is not installed. To build the full documentation:</p>
        <ol>
            <li>Install Sphinx: <code>pip install sphinx sphinx-rtd-theme</code></li>
            <li>Run the build script: <code>./build.sh</code></li>
        </ol>
        <p>Or build manually:</p>
        <code>cd docs/final/sphinx && sphinx-build -b html . _build/html</code>
    </div>
    <p>In the meantime, you can access:</p>
    <ul>
        <li><a href="../../doxygen/html/index.html">Doxygen API Reference</a></li>
        <li><a href="../../html/traceability/index.html">Traceability Matrix</a></li>
        <li><a href="../../html/misra/index.html">MISRA Compliance</a></li>
    </ul>
</body>
</html>
EOF
    fi
}

# Function to validate HTML
validate_html() {
    echo ""
    echo "Validating HTML Files..."
    echo "-------------------------"

    html_files=$(find "$OUTPUT_DIR" -name "*.html" -type f | wc -l)
    echo "Found $html_files HTML files"

    # Check for broken internal links (basic check)
    broken_links=0
    for html_file in $(find "$OUTPUT_DIR" -name "*.html" -type f); do
        # Extract href values and check if local files exist
        hrefs=$(grep -oP 'href="(?!http|#|mailto)[^"]+' "$html_file" 2>/dev/null || true)
        # This is a simplified check - full validation would use a proper HTML validator
    done

    echo -e "${GREEN}[OK]${NC} HTML validation complete"
}

# Function to create documentation archive
create_archive() {
    echo ""
    echo "Creating Documentation Archive..."
    echo "----------------------------------"

    ARCHIVE_NAME="foxbms-docs-$(date +%Y%m%d).zip"
    cd "$OUTPUT_DIR/.."

    if check_command zip; then
        zip -r "$ARCHIVE_NAME" final/ -x "*.git*"
        echo -e "${GREEN}[SUCCESS]${NC} Archive created: $ARCHIVE_NAME"
    else
        echo -e "${YELLOW}[SKIP]${NC} zip not installed"
    fi
}

# Function to display summary
show_summary() {
    echo ""
    echo "=========================================="
    echo "Build Summary"
    echo "=========================================="
    echo ""
    echo "Documentation Portal: file://$OUTPUT_DIR/index.html"
    echo ""
    echo "Available Sections:"
    echo "  - Main Portal:      $OUTPUT_DIR/index.html"
    echo "  - Sphinx Docs:      $OUTPUT_DIR/sphinx/_build/html/index.html"
    echo "  - Doxygen API:      $OUTPUT_DIR/doxygen/html/index.html"
    echo "  - Traceability:     $OUTPUT_DIR/html/traceability/index.html"
    echo "  - MISRA Compliance: $OUTPUT_DIR/html/misra/index.html"
    echo "  - Quality Metrics:  $OUTPUT_DIR/html/metrics/index.html"
    echo ""
    echo "To view locally, open in browser:"
    echo "  xdg-open $OUTPUT_DIR/index.html"
    echo ""
}

# Main execution
echo "Checking prerequisites..."
echo "-------------------------"
check_command doxygen
check_command dot
check_command sphinx-build || true
check_command python3

# Build steps
build_doxygen
build_sphinx
validate_html

# Optional: Create archive
if [ "$1" == "--archive" ]; then
    create_archive
fi

show_summary

echo -e "${GREEN}Build complete!${NC}"
